import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Paths
const excalidrawCssPath = path.resolve('node_modules/@excalidraw/excalidraw/dist/prod/index.css');
const pluginCssPath     = path.resolve('src/plugin.css');
const outputCssPath     = path.resolve('styles.css');

function buildStyles() {
	const excalidrawCss = fs.readFileSync(excalidrawCssPath, 'utf8');
	const pluginCss     = fs.readFileSync(pluginCssPath, 'utf8');
	const combined =
		'/* stylelint-disable */\n' +
		excalidrawCss +
		'\n/* stylelint-enable */\n\n' +
		pluginCss;
	fs.writeFileSync(outputCssPath, combined, 'utf8');
	console.log('[styles] styles.css rebuilt');
}

// Build styles once on startup
buildStyles();

 const cssPlugin = {
	name: 'css-rebuild',
	setup(build) {
		build.onEnd(() => {
			buildStyles();
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	jsx: 'automatic',
	jsxImportSource: 'react',
	loader: {
		'.css': 'empty',
	},
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [cssPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
